-- Script: 003-create-reservas.sql
-- Crea la tabla RESERVAS y los índices sugeridos por el usuario

CREATE TABLE reservas (
  id_reserva          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente          NUMBER(19) NOT NULL,
  id_cancha           NUMBER(19) NOT NULL,
  id_usuario_creador  NUMBER(19) NOT NULL,
  inicio_ts           TIMESTAMP  NOT NULL,
  fin_ts              TIMESTAMP  NOT NULL,
  estado              VARCHAR2(20) DEFAULT 'programada' NOT NULL,
  CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente)
    REFERENCES clientes(id_cliente),
  CONSTRAINT fk_reserva_cancha FOREIGN KEY (id_cancha)
    REFERENCES canchas(id_cancha),
  CONSTRAINT fk_reserva_creador FOREIGN KEY (id_usuario_creador)
    REFERENCES usuarios(id_usuario),
  CONSTRAINT ck_reserva_horas CHECK (fin_ts > inicio_ts),
  CONSTRAINT uq_reserva_slot UNIQUE (id_cancha, inicio_ts, fin_ts)
);

CREATE INDEX idx_reservas_cancha_inicio   ON reservas (id_cancha, inicio_ts);
CREATE INDEX idx_reservas_cliente_inicio  ON reservas (id_cliente, inicio_ts);
CREATE INDEX idx_reservas_creador_inicio  ON reservas (id_usuario_creador, inicio_ts);

-- Nota: Ejecuta este script en la base de datos Oracle del proyecto para crear la tabla.
