/* ==========================================================
   LIMPIEZA: DROP DE TODAS LAS TABLAS (SI EXISTEN)
   ========================================================== */

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_RESERVA_TERCEROS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_ALQUILA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_RESERVA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_TIPO_CANCHA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_CANCHA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_IMPLEMENTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_ADMINISTRADOR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_USUARIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

/* ==========================================================
   CREACIÓN DE TABLAS
   ========================================================== */

/* ---------- 1. USUARIO (PADRE) ---------- */
CREATE TABLE TBL_USUARIO (
    ID_USUARIO       NUMBER(10)    PRIMARY KEY,
    PRIMER_NOMBRE    VARCHAR2(50)  NOT NULL,
    SEGUNDO_NOMBRE   VARCHAR2(50),
    PRIMER_APELLIDO  VARCHAR2(50)  NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50),
    CORREO           VARCHAR2(60)  NOT NULL,
    CONTRASENA       VARCHAR2(60)  NOT NULL,
    ESTADO           VARCHAR2(50)  NOT NULL
);

/* ---------- 2. CLIENTE (HIJO DE USUARIO) ---------- */
CREATE TABLE TBL_CLIENTE (
    ID_USUARIO      NUMBER(10)    PRIMARY KEY,
    CELULAR         VARCHAR2(20) NOT NULL,
    FECHA_CREACION  DATE          NOT NULL,
    CONSTRAINT FK_TBL_CLIENTE_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES TBL_USUARIO(ID_USUARIO)
);

/* ---------- 3. ADMINISTRADOR (HIJO DE USUARIO) ---------- */
CREATE TABLE TBL_ADMINISTRADOR (
    ID_USUARIO       NUMBER(10)   PRIMARY KEY,
    FECHA_INICIO     DATE NOT NULL,
    CONSTRAINT FK_TBL_ADMIN_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES TBL_USUARIO(ID_USUARIO)
);

/* ---------- 4. IMPLEMENTO ---------- */
CREATE TABLE TBL_IMPLEMENTO (
    ID_IMPLEMENTO   NUMBER(10)    PRIMARY KEY,
    TIPO_IMPLEMENTO VARCHAR2(50)  NOT NULL,
   ESTADO          VARCHAR2(50)  NOT NULL,
   CONSTRAINT CHK_IMPLEMENTO_ESTADO CHECK (ESTADO IN ('DISPONIBLE', 'NO DISPONIBLE')),
   CANTIDAD        NUMBER(10)    NOT NULL
);

/* ---------- 5. TIPO_CANCHA (CLASIFICA CANCHAS) ---------- */
CREATE TABLE TBL_TIPO_CANCHA (
    ID_TIPO_CANCHA NUMBER(10)   PRIMARY KEY,
    NOMBRE         VARCHAR2(50) NOT NULL,
    DESCRIPCION    VARCHAR2(500) NOT NULL
);

/* ---------- 6. CANCHA (INDEPENDIENTE) ---------- */
CREATE TABLE TBL_CANCHA (
    ID_CANCHA      NUMBER(10)  PRIMARY KEY,
    ID_TIPO_CANCHA NUMBER(10)  NOT NULL,
    NOMBRE_CANCHA  VARCHAR2(50) NOT NULL,
    ESTADO        VARCHAR2(50) NOT NULL,
    HORA_APERTURA VARCHAR2(5)  NOT NULL,
    HORA_CIERRE   VARCHAR2(5)  NOT NULL,
    VALOR         NUMBER(10)   NOT NULL,
   CONSTRAINT FK_TBL_CANCHA_TIPO_CANCHA
        FOREIGN KEY (ID_TIPO_CANCHA)
        REFERENCES TBL_TIPO_CANCHA(ID_TIPO_CANCHA)
);



/* ---------- 7. RESERVA (CLIENTE HACE RESERVA DE CANCHA) ---------- */
CREATE TABLE TBL_RESERVA (
   ID_RESERVA     NUMBER(10)   PRIMARY KEY,
   ID_USUARIO     NUMBER(10)   NOT NULL,     -- debe ser CLIENTE
   ID_CANCHA      NUMBER(10)   NOT NULL,
   FECHA_RESERVA  DATE         NOT NULL,
   HORA_INICIO    VARCHAR2(5)  NOT NULL,
   HORA_FIN       VARCHAR2(5)  NOT NULL,
   ESTADO         VARCHAR2(50) NOT NULL,
    
   CONSTRAINT FK_RESERVA_USUARIO
      FOREIGN KEY (ID_USUARIO)
      REFERENCES TBL_CLIENTE(ID_USUARIO),

   CONSTRAINT FK_RESERVA_CANCHA
      FOREIGN KEY (ID_CANCHA)
      REFERENCES TBL_CANCHA(ID_CANCHA)
);

/* ---------- 8. RESERVA_TERCEROS (ADMINISTRADOR ↔ RESERVA) ---------- */
CREATE TABLE TBL_RESERVA_TERCEROS (
   ID_RESERVA_TERCERO NUMBER(10) PRIMARY KEY,
   ID_USUARIO         NUMBER(10) NOT NULL,   -- administrador
   CONTACTO_TERCERO   VARCHAR2(20) NOT NULL,
   NOMBRE_TERCERO     VARCHAR2(50) NOT NULL,
   ID_CANCHA          NUMBER(10) NOT NULL,
   FECHA_RESERVA      DATE NOT NULL,
   HORA_INICIO        VARCHAR2(5) NOT NULL,
   HORA_FIN           VARCHAR2(5) NOT NULL,
   ESTADO             VARCHAR2(50) NOT NULL,

   CONSTRAINT FK_RESERVA_TERCERO_ADMIN
      FOREIGN KEY (ID_USUARIO)
      REFERENCES TBL_ADMINISTRADOR(ID_USUARIO),
    
   CONSTRAINT FK_RESERVA_TERCERO_CANCHA
      FOREIGN KEY (ID_CANCHA)
      REFERENCES TBL_CANCHA(ID_CANCHA)
);


/* ---------- 10. ALQUILA (CLIENTE ↔ IMPLEMENTO, INDEPENDIENTE DE RESERVA) ---------- */
CREATE TABLE TBL_ALQUILA (
    ID_PRESTAMO      NUMBER(10)   PRIMARY KEY,
    ID_USUARIO       NUMBER(10)   NOT NULL,   -- cliente
    ID_IMPLEMENTO    NUMBER(10)   NOT NULL,   -- implemento
    FECHA_PRESTAMO   DATE         NOT NULL,
    HORA_PRESTAMO    VARCHAR2(5 BYTE)         NOT NULL,
    FECHA_DEVOLUCION DATE         NOT NULL,
    CONSTRAINT FK_TBL_ALQUILA_CLIENTE
        FOREIGN KEY (ID_USUARIO)
        REFERENCES TBL_CLIENTE(ID_USUARIO),
    CONSTRAINT FK_TBL_ALQUILA_IMPLEMENTO
        FOREIGN KEY (ID_IMPLEMENTO)
        REFERENCES TBL_IMPLEMENTO(ID_IMPLEMENTO)
);

/* ==========================================================
   ÍNDICES OPCIONALES PARA MEJORAR PERFORMANCE
   ========================================================== */

CREATE INDEX IDX_RESERVA_USUARIO      ON TBL_RESERVA(ID_USUARIO);
CREATE INDEX IDX_RESERVA_CANCHA       ON TBL_RESERVA(ID_CANCHA);

CREATE INDEX IDX_RES_TERC_RESERVA     ON TBL_RESERVA_TERCEROS(ID_RESERVA_TERCERO);
CREATE INDEX IDX_RES_TERC_ADMIN       ON TBL_RESERVA_TERCEROS(ID_USUARIO);

CREATE INDEX IDX_ALQUILA_USUARIO      ON TBL_ALQUILA(ID_USUARIO);
CREATE INDEX IDX_ALQUILA_IMPLEMENTO   ON TBL_ALQUILA(ID_IMPLEMENTO);
