/* ==========================================================
   CREACIÓN DE USUARIO Y ASIGNACIÓN DE PRIVILEGIOS
   ========================================================== */

ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER PROYECTO_B2IDENTIFIED BY oracle;
GRANT CONNECT TO PROYECTO_BD2;
GRANT RESOURCE TO PROYECTO_BD2;
GRANT DBA TO PROYECTO_BD2;


/* ==========================================================
   LIMPIEZA: DROP DE TODAS LAS TABLAS (SI EXISTEN)
   ========================================================== */

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_RESERVA_TERCEROS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_ALQUILA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_RESERVA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_TIPO_CANCHA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_CANCHA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_IMPLEMENTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_ADMINISTRADOR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TBL_USUARIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

/* ==========================================================
   CREACIÓN DE TABLAS
   ========================================================== */

/* ---------- 1. USUARIO (PADRE) ---------- */
CREATE TABLE TBL_USUARIO (
    ID_USUARIO       NUMBER(10)    PRIMARY KEY,
    PRIMER_NOMBRE    VARCHAR2(50)  NOT NULL,
    SEGUNDO_NOMBRE   VARCHAR2(50),
    PRIMER_APELLIDO  VARCHAR2(50)  NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50),
    CORREO           VARCHAR2(60)  NOT NULL,
    CONTRASENA       VARCHAR2(60)  NOT NULL,
    ESTADO           VARCHAR2(50)  NOT NULL
);

/* ---------- 2. CLIENTE (HIJO DE USUARIO) ---------- */
CREATE TABLE TBL_CLIENTE (
    ID_USUARIO      NUMBER(10)    PRIMARY KEY,
    CELULAR         VARCHAR2(20) NOT NULL,
    FECHA_CREACION  DATE          NOT NULL,
    CONSTRAINT FK_TBL_CLIENTE_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES TBL_USUARIO(ID_USUARIO)
);

/* ---------- 3. ADMINISTRADOR (HIJO DE USUARIO) ---------- */
CREATE TABLE TBL_ADMINISTRADOR (
    ID_USUARIO       NUMBER(10)   PRIMARY KEY,
    FECHA_INICIO     DATE NOT NULL,
    CONSTRAINT FK_TBL_ADMIN_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES TBL_USUARIO(ID_USUARIO)
);

/* ---------- 4. IMPLEMENTO ---------- */
CREATE TABLE TBL_IMPLEMENTO (
    ID_IMPLEMENTO   NUMBER(10)    PRIMARY KEY,
    TIPO_IMPLEMENTO VARCHAR2(50)  NOT NULL,
    ESTADO          VARCHAR2(50)  NOT NULL,
    CONSTRAINT CHK_IMPLEMENTO_ESTADO CHECK (ESTADO IN ('DISPONIBLE', 'NO DISPONIBLE')),
    CANTIDAD        NUMBER(10)    NOT NULL
);

/* ---------- 5. TIPO_CANCHA (CLASIFICA CANCHAS) ---------- */
CREATE TABLE TBL_TIPO_CANCHA (
    ID_TIPO_CANCHA NUMBER(10)   PRIMARY KEY,
    NOMBRE         VARCHAR2(50) NOT NULL,
    DESCRIPCION    VARCHAR2(500) NOT NULL
);

/* ---------- 6. CANCHA (INDEPENDIENTE) ---------- */
CREATE TABLE TBL_CANCHA (
    ID_CANCHA      NUMBER(10)  PRIMARY KEY,
    ID_TIPO_CANCHA NUMBER(10)  NOT NULL,
    NOMBRE_CANCHA  VARCHAR2(50) NOT NULL,
    ESTADO        VARCHAR2(50) NOT NULL,
    HORA_APERTURA VARCHAR2(5 BYTE) NOT NULL,
    HORA_CIERRE   VARCHAR2(5 BYTE) NOT NULL,
    VALOR         NUMBER(10)   NOT NULL,
   CONSTRAINT FK_TBL_CANCHA_TIPO_CANCHA
        FOREIGN KEY (ID_TIPO_CANCHA)
        REFERENCES TBL_TIPO_CANCHA(ID_TIPO_CANCHA)
);



/* ---------- 7. RESERVA (CLIENTE HACE RESERVA DE CANCHA) ---------- */
CREATE TABLE TBL_RESERVA (
    ID_RESERVA     NUMBER(10)   PRIMARY KEY,
    ID_USUARIO     NUMBER(10)   NOT NULL,     -- debe ser CLIENTE
    ID_CANCHA      NUMBER(10)   NOT NULL,
    FECHA_RESERVA  DATE         NOT NULL,
    HORA_INICIO    VARCHAR2(5 BYTE) NOT NULL,
    HORA_FIN       VARCHAR2(5 BYTE) NOT NULL,
    ESTADO         VARCHAR2(50) NOT NULL,
    
    CONSTRAINT FK_RESERVA_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES TBL_CLIENTE(ID_USUARIO),

    CONSTRAINT FK_RESERVA_CANCHA
        FOREIGN KEY (ID_CANCHA)
        REFERENCES TBL_CANCHA(ID_CANCHA)
);



/* ---------- 8. RESERVA_TERCEROS (ADMINISTRADOR ↔ RESERVA) ---------- */
CREATE TABLE TBL_RESERVA_TERCEROS (
    ID_RESERVA_TERCERO NUMBER(10) PRIMARY KEY,
    ID_USUARIO         NUMBER(10) NOT NULL,   -- administrador
    CONTACTO_TERCERO   VARCHAR2(20) NOT NULL,
    NOMBRE_TERCERO     VARCHAR2(50) NOT NULL,
    ID_CANCHA          NUMBER(10) NOT NULL,
    FECHA_RESERVA      DATE NOT NULL,
    HORA_INICIO        VARCHAR2(5 BYTE) NOT NULL,
    HORA_FIN           VARCHAR2(5 BYTE) NOT NULL,
    ESTADO             VARCHAR2(50) NOT NULL,

    CONSTRAINT FK_RESERVA_TERCERO_ADMIN
        FOREIGN KEY (ID_USUARIO)
        REFERENCES TBL_ADMINISTRADOR(ID_USUARIO),
    
    CONSTRAINT FK_RESERVA_TERCERO_CANCHA
        FOREIGN KEY (ID_CANCHA)
        REFERENCES TBL_CANCHA(ID_CANCHA)
);


/* ---------- 10. ALQUILA (CLIENTE ↔ IMPLEMENTO, INDEPENDIENTE DE RESERVA) ---------- */
CREATE TABLE TBL_ALQUILA (
    ID_PRESTAMO      NUMBER(10)   PRIMARY KEY,
    ID_USUARIO       NUMBER(10)   NOT NULL,   -- cliente
    ID_IMPLEMENTO    NUMBER(10)   NOT NULL,   -- implemento
    CANTIDAD_PRESTADA    NUMBER(10)   NOT NULL,
    FECHA_PRESTAMO   DATE         NOT NULL,
    HORA_PRESTAMO    VARCHAR2(5 BYTE) NOT NULL,
    FECHA_DEVOLUCION DATE,
    CONSTRAINT FK_TBL_ALQUILA_CLIENTE
        FOREIGN KEY (ID_USUARIO)
        REFERENCES TBL_CLIENTE(ID_USUARIO),
    CONSTRAINT FK_TBL_ALQUILA_IMPLEMENTO
        FOREIGN KEY (ID_IMPLEMENTO)
        REFERENCES TBL_IMPLEMENTO(ID_IMPLEMENTO)
);

/* ==========================================================
   ÍNDICES OPCIONALES PARA MEJORAR PERFORMANCE
   ========================================================== */

CREATE INDEX IDX_RESERVA_USUARIO      ON TBL_RESERVA(ID_USUARIO);
CREATE INDEX IDX_RESERVA_CANCHA       ON TBL_RESERVA(ID_CANCHA);

CREATE INDEX IDX_RES_TERC_ADMIN       ON TBL_RESERVA_TERCEROS(ID_USUARIO);

CREATE INDEX IDX_ALQUILA_USUARIO      ON TBL_ALQUILA(ID_USUARIO);
CREATE INDEX IDX_ALQUILA_IMPLEMENTO   ON TBL_ALQUILA(ID_IMPLEMENTO);


/* ==========================================================
   SECUENCIAS PARA TODAS LAS TABLAS
   ========================================================== */

CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ADMINISTRADOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IMPLEMENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TIPO_CANCHA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CANCHA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESERVA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESERVA_TERCEROS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DESCUENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALQUILA START WITH 1 INCREMENT BY 1;



/* ==========================================================
   TRIGGERS PARA ASIGNAR IDs AUTOMÁTICOS
   ========================================================== */

/* ---------- 1. USUARIO ---------- */
CREATE OR REPLACE TRIGGER TRG_USUARIO_PK
BEFORE INSERT ON TBL_USUARIO
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    SELECT SEQ_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM dual;
  END IF;
END;
/

/* ---------- 2. CLIENTE ---------- */
CREATE OR REPLACE TRIGGER TRG_CLIENTE_PK
BEFORE INSERT ON TBL_CLIENTE
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    SELECT SEQ_CLIENTE.NEXTVAL INTO :NEW.ID_USUARIO FROM dual;
  END IF;
END;
/

/* ---------- 3. ADMINISTRADOR ---------- */
CREATE OR REPLACE TRIGGER TRG_ADMINISTRADOR_PK
BEFORE INSERT ON TBL_ADMINISTRADOR
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    SELECT SEQ_ADMINISTRADOR.NEXTVAL INTO :NEW.ID_USUARIO FROM dual;
  END IF;
END;
/

/* ---------- 4. IMPLEMENTO ---------- */
CREATE OR REPLACE TRIGGER TRG_IMPLEMENTO_PK
BEFORE INSERT ON TBL_IMPLEMENTO
FOR EACH ROW
BEGIN
  IF :NEW.ID_IMPLEMENTO IS NULL THEN
    SELECT SEQ_IMPLEMENTO.NEXTVAL INTO :NEW.ID_IMPLEMENTO FROM dual;
  END IF;
END;
/

/* ---------- 5. TIPO_CANCHA ---------- */
CREATE OR REPLACE TRIGGER TRG_TIPO_CANCHA_PK
BEFORE INSERT ON TBL_TIPO_CANCHA
FOR EACH ROW
BEGIN
  IF :NEW.ID_TIPO_CANCHA IS NULL THEN
    SELECT SEQ_TIPO_CANCHA.NEXTVAL INTO :NEW.ID_TIPO_CANCHA FROM dual;
  END IF;
END;
/

/* ---------- 6. CANCHA ---------- */
CREATE OR REPLACE TRIGGER TRG_CANCHA_PK
BEFORE INSERT ON TBL_CANCHA
FOR EACH ROW
BEGIN
  IF :NEW.ID_CANCHA IS NULL THEN
    SELECT SEQ_CANCHA.NEXTVAL INTO :NEW.ID_CANCHA FROM dual;
  END IF;
END;
/

/* ---------- 7. RESERVA ---------- */
CREATE OR REPLACE TRIGGER TRG_RESERVA_PK
BEFORE INSERT ON TBL_RESERVA
FOR EACH ROW
BEGIN
  IF :NEW.ID_RESERVA IS NULL THEN
    SELECT SEQ_RESERVA.NEXTVAL INTO :NEW.ID_RESERVA FROM dual;
  END IF;
END;
/

/* ---------- 8. RESERVA_TERCEROS ---------- */
CREATE OR REPLACE TRIGGER TRG_RESERVA_TERCEROS_PK
BEFORE INSERT ON TBL_RESERVA_TERCEROS
FOR EACH ROW
BEGIN
  IF :NEW.ID_RESERVA_TERCERO IS NULL THEN
    SELECT SEQ_RESERVA_TERCEROS.NEXTVAL INTO :NEW.ID_RESERVA_TERCERO FROM dual;
  END IF;
END;
/



/* ---------- 10. ALQUILA ---------- */
CREATE OR REPLACE TRIGGER TRG_ALQUILA_PK
BEFORE INSERT ON TBL_ALQUILA
FOR EACH ROW
BEGIN
  IF :NEW.ID_PRESTAMO IS NULL THEN
    SELECT SEQ_ALQUILA.NEXTVAL INTO :NEW.ID_PRESTAMO FROM dual;
  END IF;
END;
/


/* ==========================================================
   DML INICIAL - PROYECTO CLUB LOS ROBLES
   Tablas según DDL enviado (TBL_USUARIO, TBL_CLIENTE, etc.)
   ========================================================== */

-------------------------------------------------------------
-- 1. USUARIOS + ADMINISTRADORES (5)
--    FECHA_INICIO es NOT NULL → se asigna SYSDATE
-------------------------------------------------------------

-- Admin 1: Camilo
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'Camilo', NULL,
    'Ríos', 'Torres',
    'camilo@losrobles.com', 'admin01', 'ACTIVO'
);

INSERT INTO TBL_ADMINISTRADOR (ID_USUARIO, FECHA_INICIO)
VALUES (
    SEQ_USUARIO.CURRVAL,
    SYSDATE
);

-- Admin 2: Natalia
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'Natalia', NULL,
    'Gallego', 'Yepes',
    'natalia@losrobles.com', 'admin02', 'ACTIVO'
);

INSERT INTO TBL_ADMINISTRADOR (ID_USUARIO, FECHA_INICIO)
VALUES (
    SEQ_USUARIO.CURRVAL,
    SYSDATE
);

-- Admin 3: Santiago
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'Santiago', NULL,
    'López', 'Martínez',
    'santiago@losrobles.com', 'admin03', 'ACTIVO'
);

INSERT INTO TBL_ADMINISTRADOR (ID_USUARIO, FECHA_INICIO)
VALUES (
    SEQ_USUARIO.CURRVAL,
    SYSDATE
);

-- Admin 4: Juliana
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'Juliana', NULL,
    'Moreno', 'Pérez',
    'juliana@losrobles.com', 'admin04', 'ACTIVO'
);

INSERT INTO TBL_ADMINISTRADOR (ID_USUARIO, FECHA_INICIO)
VALUES (
    SEQ_USUARIO.CURRVAL,
    SYSDATE
);

-- Admin 5: Mateo
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'Mateo', NULL,
    'Cruz', 'Ramírez',
    'mateo@losrobles.com', 'admin05', 'ACTIVO'
);

INSERT INTO TBL_ADMINISTRADOR (ID_USUARIO, FECHA_INICIO)
VALUES (
    SEQ_USUARIO.CURRVAL,
    SYSDATE
);



-------------------------------------------------------------
-- 2. USUARIOS + CLIENTES (5)
--    FECHA_CREACION es NOT NULL → se asigna SYSDATE
-------------------------------------------------------------

-- Cliente 1: Laura
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'Laura', 'Valentina',
    'Gonzalez', 'Tulcan',
    'laura.gt@gmail.com', 'cli01', 'ACTIVO'
);

INSERT INTO TBL_CLIENTE (ID_USUARIO, CELULAR, FECHA_CREACION)
VALUES (
    SEQ_USUARIO.CURRVAL,
    '3001112233',
    SYSDATE
);

-- Cliente 2: Andrés
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'Andrés', NULL,
    'Fernández', 'Quintero',
    'andres.fq@gmail.com', 'cli02', 'ACTIVO'
);

INSERT INTO TBL_CLIENTE (ID_USUARIO, CELULAR, FECHA_CREACION)
VALUES (
    SEQ_USUARIO.CURRVAL,
    '3002223344',
    SYSDATE
);

-- Cliente 3: María José
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'María', 'José',
    'Suárez', 'Herrera',
    'mariajh@gmail.com', 'cli03', 'ACTIVO'
);

INSERT INTO TBL_CLIENTE (ID_USUARIO, CELULAR, FECHA_CREACION)
VALUES (
    SEQ_USUARIO.CURRVAL,
    '3003334455',
    SYSDATE
);

-- Cliente 4: Daniel
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'Daniel', NULL,
    'Ospina', 'Luna',
    'daniel.ol@gmail.com', 'cli04', 'ACTIVO'
);

INSERT INTO TBL_CLIENTE (ID_USUARIO, CELULAR, FECHA_CREACION)
VALUES (
    SEQ_USUARIO.CURRVAL,
    '3004445566',
    SYSDATE
);

-- Cliente 5: Sara
INSERT INTO TBL_USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE, SEGUNDO_NOMBRE,
    PRIMER_APELLIDO, SEGUNDO_APELLIDO,
    CORREO, CONTRASENA, ESTADO
) VALUES (
    NULL,
    'Sara', NULL,
    'Ramírez', 'Gómez',
    'sararg@gmail.com', 'cli05', 'ACTIVO'
);

INSERT INTO TBL_CLIENTE (ID_USUARIO, CELULAR, FECHA_CREACION)
VALUES (
    SEQ_USUARIO.CURRVAL,
    '3005556677',
    SYSDATE
);



-------------------------------------------------------------
-- 3. TIPO_CANCHA
-------------------------------------------------------------
INSERT INTO TBL_TIPO_CANCHA (ID_TIPO_CANCHA, NOMBRE, DESCRIPCION)
VALUES (1, 'Fútbol', 'Cancha de césped natural o sintético para partidos de fútbol.');

INSERT INTO TBL_TIPO_CANCHA (ID_TIPO_CANCHA, NOMBRE, DESCRIPCION)
VALUES (2, 'Baloncesto', 'Cancha con tablero y aro, utilizada para juegos de baloncesto.');

INSERT INTO TBL_TIPO_CANCHA (ID_TIPO_CANCHA, NOMBRE, DESCRIPCION)
VALUES (3, 'Voleibol', 'Cancha dividida por una red central para partidos de voleibol.');

INSERT INTO TBL_TIPO_CANCHA (ID_TIPO_CANCHA, NOMBRE, DESCRIPCION)
VALUES (4, 'Tenis', 'Cancha con superficie dura, arcilla o césped, dividida por una red.');



-------------------------------------------------------------
-- 4. IMPLEMENTOS
--    Se asume trigger PK para ID_IMPLEMENTO (por eso va NULL)
-------------------------------------------------------------
INSERT INTO TBL_IMPLEMENTO (ID_IMPLEMENTO, TIPO_IMPLEMENTO, ESTADO, CANTIDAD)
VALUES (NULL, 'Balón fútbol N°5',       'DISPONIBLE', 10);

INSERT INTO TBL_IMPLEMENTO (ID_IMPLEMENTO, TIPO_IMPLEMENTO, ESTADO, CANTIDAD)
VALUES (NULL, 'Balón baloncesto',       'DISPONIBLE', 8);

INSERT INTO TBL_IMPLEMENTO (ID_IMPLEMENTO, TIPO_IMPLEMENTO, ESTADO, CANTIDAD)
VALUES (NULL, 'Red de voleibol',        'DISPONIBLE', 5);

INSERT INTO TBL_IMPLEMENTO (ID_IMPLEMENTO, TIPO_IMPLEMENTO, ESTADO, CANTIDAD)
VALUES (NULL, 'Raqueta de tenis',       'DISPONIBLE', 12);

INSERT INTO TBL_IMPLEMENTO (ID_IMPLEMENTO, TIPO_IMPLEMENTO, ESTADO, CANTIDAD)
VALUES (NULL, 'Conos de entrenamiento', 'DISPONIBLE', 20);



-------------------------------------------------------------
-- 5. CANCHAS
--    Se asume trigger PK para ID_CANCHA (por eso va NULL)
-------------------------------------------------------------
-- Cancha 1: Fútbol
INSERT INTO TBL_CANCHA (
    ID_CANCHA, ID_TIPO_CANCHA, NOMBRE_CANCHA,
    ESTADO, HORA_APERTURA, HORA_CIERRE, VALOR
) VALUES (
    NULL,
    1,
    'Cancha Fútbol 1',
    'DISPONIBLE',
    '08:00',
    '22:00',
    80000
);

-- Cancha 2: Baloncesto
INSERT INTO TBL_CANCHA (
    ID_CANCHA, ID_TIPO_CANCHA, NOMBRE_CANCHA,
    ESTADO, HORA_APERTURA, HORA_CIERRE, VALOR
) VALUES (
    NULL,
    2,
    'Cancha Baloncesto 1',
    'DISPONIBLE',
    '09:00',
    '21:00',
    60000
);

-- Cancha 3: Voleibol
INSERT INTO TBL_CANCHA (
    ID_CANCHA, ID_TIPO_CANCHA, NOMBRE_CANCHA,
    ESTADO, HORA_APERTURA, HORA_CIERRE, VALOR
) VALUES (
    NULL,
    3,
    'Cancha Voleibol 1',
    'DISPONIBLE',
    '10:00',
    '20:00',
    50000
);

-- Cancha 4: Tenis
INSERT INTO TBL_CANCHA (
    ID_CANCHA, ID_TIPO_CANCHA, NOMBRE_CANCHA,
    ESTADO, HORA_APERTURA, HORA_CIERRE, VALOR
) VALUES (
    NULL,
    4,
    'Cancha Tenis 1',
    'DISPONIBLE',
    '07:00',
    '19:00',
    70000
);



/* ==========================================================
   6. RESERVAS DE CLIENTES (TBL_RESERVA)
   HORA_INICIO / HORA_FIN: VARCHAR2(5) 'HH24:MI'
   ========================================================== */

-- Reserva 1: Laura, cancha de fútbol (18:00 - 19:00)
INSERT INTO TBL_RESERVA (
    ID_RESERVA, ID_USUARIO, ID_CANCHA,
    FECHA_RESERVA, HORA_INICIO, HORA_FIN, ESTADO
) VALUES (
    NULL,
    (SELECT c.ID_USUARIO
       FROM TBL_CLIENTE c
       JOIN TBL_USUARIO u ON u.ID_USUARIO = c.ID_USUARIO
      WHERE u.CORREO = 'laura.gt@gmail.com'
        AND ROWNUM = 1),
    (SELECT ID_CANCHA
       FROM TBL_CANCHA
      WHERE NOMBRE_CANCHA = 'Cancha Fútbol 1'
        AND ROWNUM = 1),
    TO_DATE('2024-11-20', 'YYYY-MM-DD'),
    '18:00',
    '19:00',
    'CONFIRMADA'
);

-- Reserva 2: Andrés, cancha de baloncesto (16:00 - 17:00)
INSERT INTO TBL_RESERVA (
    ID_RESERVA, ID_USUARIO, ID_CANCHA,
    FECHA_RESERVA, HORA_INICIO, HORA_FIN, ESTADO
) VALUES (
    NULL,
    (SELECT c.ID_USUARIO
       FROM TBL_CLIENTE c
       JOIN TBL_USUARIO u ON u.ID_USUARIO = c.ID_USUARIO
      WHERE u.CORREO = 'andres.fq@gmail.com'
        AND ROWNUM = 1),
    (SELECT ID_CANCHA
       FROM TBL_CANCHA
      WHERE NOMBRE_CANCHA = 'Cancha Baloncesto 1'
        AND ROWNUM = 1),
    TO_DATE('2024-11-21', 'YYYY-MM-DD'),
    '16:00',
    '17:00',
    'CONFIRMADA'
);

-- Reserva 3: María, cancha de tenis (09:00 - 10:00)
INSERT INTO TBL_RESERVA (
    ID_RESERVA, ID_USUARIO, ID_CANCHA,
    FECHA_RESERVA, HORA_INICIO, HORA_FIN, ESTADO
) VALUES (
    NULL,
    (SELECT c.ID_USUARIO
       FROM TBL_CLIENTE c
       JOIN TBL_USUARIO u ON u.ID_USUARIO = c.ID_USUARIO
      WHERE u.CORREO = 'mariajh@gmail.com'
        AND ROWNUM = 1),
    (SELECT ID_CANCHA
       FROM TBL_CANCHA
      WHERE NOMBRE_CANCHA = 'Cancha Tenis 1'
        AND ROWNUM = 1),
    TO_DATE('2024-11-22', 'YYYY-MM-DD'),
    '09:00',
    '10:00',
    'PENDIENTE'
);



/* ==========================================================
   7. RESERVAS DE TERCEROS (TBL_RESERVA_TERCEROS)
   SOLO ADMIN (FK a TBL_ADMINISTRADOR)
   ========================================================== */

-- Reserva terceros 1: Camilo para Empresa ACME (Baloncesto)
INSERT INTO TBL_RESERVA_TERCEROS (
    ID_RESERVA_TERCERO, ID_USUARIO,
    CONTACTO_TERCERO, NOMBRE_TERCERO,
    ID_CANCHA, FECHA_RESERVA, HORA_INICIO, HORA_FIN, ESTADO
) VALUES (
    NULL,
    (SELECT a.ID_USUARIO
       FROM TBL_ADMINISTRADOR a
       JOIN TBL_USUARIO u ON u.ID_USUARIO = a.ID_USUARIO
      WHERE u.CORREO = 'camilo@losrobles.com'
        AND ROWNUM = 1),
    '3009991122',
    'Empresa ACME',
    (SELECT ID_CANCHA
       FROM TBL_CANCHA
      WHERE NOMBRE_CANCHA = 'Cancha Baloncesto 1'
        AND ROWNUM = 1),
    TO_DATE('2024-11-23', 'YYYY-MM-DD'),
    '10:00',
    '11:00',
    'CONFIRMADA'
);

-- Reserva terceros 2: Natalia para Torneo Intercolegial (Fútbol)
INSERT INTO TBL_RESERVA_TERCEROS (
    ID_RESERVA_TERCERO, ID_USUARIO,
    CONTACTO_TERCERO, NOMBRE_TERCERO,
    ID_CANCHA, FECHA_RESERVA, HORA_INICIO, HORA_FIN, ESTADO
) VALUES (
    NULL,
    (SELECT a.ID_USUARIO
       FROM TBL_ADMINISTRADOR a
       JOIN TBL_USUARIO u ON u.ID_USUARIO = a.ID_USUARIO
      WHERE u.CORREO = 'natalia@losrobles.com'
        AND ROWNUM = 1),
    '3018882233',
    'Torneo Intercolegial',
    (SELECT ID_CANCHA
       FROM TBL_CANCHA
      WHERE NOMBRE_CANCHA = 'Cancha Fútbol 1'
        AND ROWNUM = 1),
    TO_DATE('2024-11-24', 'YYYY-MM-DD'),
    '14:00',
    '15:00',
    'CONFIRMADA'
);



/* ==========================================================
   8. PRÉSTAMOS DE IMPLEMENTOS (TBL_ALQUILA)
   HORA_PRESTAMO: VARCHAR2(5)
   ========================================================== */

-- Préstamo 1: Laura lleva balón de fútbol
INSERT INTO TBL_ALQUILA (
    ID_PRESTAMO, ID_USUARIO, ID_IMPLEMENTO, CANTIDAD_PRESTADA,
    FECHA_PRESTAMO, HORA_PRESTAMO, FECHA_DEVOLUCION
) VALUES (
    NULL,
    (SELECT c.ID_USUARIO
       FROM TBL_CLIENTE c
       JOIN TBL_USUARIO u ON u.ID_USUARIO = c.ID_USUARIO
      WHERE u.CORREO = 'laura.gt@gmail.com'
        AND ROWNUM = 1),
    (SELECT ID_IMPLEMENTO
       FROM TBL_IMPLEMENTO
      WHERE TIPO_IMPLEMENTO = 'Balón fútbol N°5'
        AND ROWNUM = 1),
    1,
    TO_DATE('2024-11-20', 'YYYY-MM-DD'),
    '17:30',
    TO_DATE('2024-11-20 19:30', 'YYYY-MM-DD HH24:MI')
);

-- Préstamo 2: Andrés lleva balón de baloncesto
INSERT INTO TBL_ALQUILA (
    ID_PRESTAMO, ID_USUARIO, ID_IMPLEMENTO, CANTIDAD_PRESTADA,
    FECHA_PRESTAMO, HORA_PRESTAMO, FECHA_DEVOLUCION
) VALUES (
    NULL,
    (SELECT c.ID_USUARIO
       FROM TBL_CLIENTE c
       JOIN TBL_USUARIO u ON u.ID_USUARIO = c.ID_USUARIO
      WHERE u.CORREO = 'andres.fq@gmail.com'
        AND ROWNUM = 1),
    (SELECT ID_IMPLEMENTO
       FROM TBL_IMPLEMENTO
      WHERE TIPO_IMPLEMENTO = 'Balón baloncesto'
        AND ROWNUM = 1),
    1,
    TO_DATE('2024-11-21', 'YYYY-MM-DD'),
    '15:30',
    TO_DATE('2024-11-21 18:30', 'YYYY-MM-DD HH24:MI')
);

-- Préstamo 3: María lleva raqueta de tenis
INSERT INTO TBL_ALQUILA (
    ID_PRESTAMO, ID_USUARIO, ID_IMPLEMENTO, CANTIDAD_PRESTADA,
    FECHA_PRESTAMO, HORA_PRESTAMO, FECHA_DEVOLUCION
) VALUES (
    NULL,
    (SELECT c.ID_USUARIO
       FROM TBL_CLIENTE c
       JOIN TBL_USUARIO u ON u.ID_USUARIO = c.ID_USUARIO
      WHERE u.CORREO = 'mariajh@gmail.com'
        AND ROWNUM = 1),
    (SELECT ID_IMPLEMENTO
       FROM TBL_IMPLEMENTO
      WHERE TIPO_IMPLEMENTO = 'Raqueta de tenis'
        AND ROWNUM = 1),
    1,
    TO_DATE('2024-11-22', 'YYYY-MM-DD'),
    '08:00',
    TO_DATE('2024-11-22 10:00', 'YYYY-MM-DD HH24:MI')
);

COMMIT;
